name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: curl -X GET "https://qmag.sbquantum.com//run-integration-tests?owner=${{ github.repository_owner }}&repo=${{ github.event.repository.name }}&commit_sha=${{ github.sha }}"
