name: GitHub Actions Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: printf "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: ssh 3.95.15.232
