name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
             curl  --header "X-API-KEY: fe17ac1718f880be029ef3b4c41fbe96247b2cb3302455e24f12541dd0daaade" "https://qmag.sbquantum.com/run-integration-tests?owner=${{ github.repository_owner }}&repo=${{ github.event.repository.name }}&commit_sha=${{ github.sha }}" 
